/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "secondary": "#c8c6c5",
        "surface-tint": "#ffb4a8",
        "on-tertiary": "#68000a",
        "surface-container-highest": "#33343c",
        "outline-variant": "#5e3f3a",
        "primary": "#ffb4a8",
        "tertiary-container": "#d32f33",
        "tertiary-fixed": "#ffdad7",
        "secondary-fixed": "#e5e2e1",
        "surface-container-high": "#292931",
        "on-primary": "#680200",
        "on-tertiary-container": "#fff2f0",
        "inverse-on-surface": "#2f3038",
        "surface-container": "#1e1f26",
        "tertiary-fixed-dim": "#ffb3ad",
        "surface-container-low": "#1a1b22",
        "inverse-primary": "#c00500",
        "primary-container": "#e10600",
        "on-surface-variant": "#e9bcb5",
        "on-primary-fixed-variant": "#930300",
        "surface-bright": "#383941",
        "on-primary-container": "#fff2f0",
        "on-background": "#e3e1ec",
        "surface-variant": "#33343c",
        "on-error": "#690005",
        "on-secondary-fixed": "#1c1b1b",
        "secondary-container": "#474746",
        "on-primary-fixed": "#410100",
        "on-tertiary-fixed": "#410004",
        "inverse-surface": "#e3e1ec",
        "surface-dim": "#12131a",
        "surface-container-lowest": "#0d0e15",
        "primary-fixed": "#ffdad4",
        "outline": "#af8781",
        "on-tertiary-fixed-variant": "#930013",
        "on-secondary-container": "#b7b4b4",
        "surface": "#12131a",
        "tertiary": "#ffb3ad",
        "primary-fixed-dim": "#ffb4a8",
        "on-secondary-fixed-variant": "#474746",
        "on-secondary": "#313030",
        "on-surface": "#e3e1ec",
        "on-error-container": "#ffdad6",
        "background": "#12131a",
        "error-container": "#93000a",
        "error": "#ffb4ab",
        "secondary-fixed-dim": "#c8c6c5"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "sm": "0.125rem",
        "md": "0.25rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "margin-desktop": "2.5rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "margin": "1rem",
        "margin-tablet": "1.5rem",
        "gutter-desktop": "1.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2.5rem",
        "gutter": "1rem"
      },
      fontFamily: {
        "headline-sm": ["Oswald", "sans-serif"],
        "metric-md": ["Oswald", "sans-serif"],
        "display-hero-mobile": ["Oswald", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-caps": ["Oswald", "sans-serif"],
        "headline-lg-mobile": ["Oswald", "sans-serif"],
        "metric-xl": ["Oswald", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "headline-lg": ["Oswald", "sans-serif"],
        "headline-md": ["Oswald", "sans-serif"],
        "label-mono": ["Inter", "sans-serif"],
        "display-hero": ["Oswald", "sans-serif"],
        "sans": ["Inter", "sans-serif"],
        "oswald": ["Oswald", "sans-serif"]
      },
      fontSize: {
        "headline-sm": ["18px", { lineHeight: "22px", letterSpacing: "0.02em", fontWeight: "600" }],
        "metric-md": ["32px", { lineHeight: "34px", letterSpacing: "0em", fontWeight: "700" }],
        "display-hero-mobile": ["44px", { lineHeight: "48px", letterSpacing: "0.03em", fontWeight: "700" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "500" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.08em", fontWeight: "600" }],
        "headline-lg-mobile": ["28px", { lineHeight: "32px", letterSpacing: "0.02em", fontWeight: "700" }],
        "metric-xl": ["56px", { lineHeight: "56px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "headline-lg": ["36px", { lineHeight: "40px", letterSpacing: "0.02em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "28px", letterSpacing: "0.01em", fontWeight: "600" }],
        "label-mono": ["11px", { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "600" }],
        "display-hero": ["64px", { lineHeight: "68px", letterSpacing: "0.04em", fontWeight: "700" }]
      }
    },
  },
  plugins: [],
}
