const express = require('express');
const router = express.Router();
const { protect } = require('../middleware/authMiddleware');
const validate = require('../middleware/validateMiddleware');
const { aiChatSchema } = require('../validations/schemas');

// AI Coach Intelligent Advice & Response Generator
const generateAICoachResponse = (prompt, context) => {
  const lower = prompt.toLowerCase();
  
  if (lower.includes('workout') || lower.includes('exercise') || lower.includes('lift') || lower.includes('hypertrophy')) {
    return {
      reply: "Based on your current telemetry and CNS readiness (94%), progressive overload is recommended for today's session. Target 3-4 sets of 8-10 reps on compound movements with RPE 8-9. Ensure a 120s rest interval between working sets to maximize myofibrillar protein synthesis.",
      actionableTip: "Keep eccentric control to 3 seconds for optimum tension.",
      disclaimer: "All athletic recommendations and health estimations provided are estimates for reference only and do not constitute medical advice."
    };
  }

  if (lower.includes('food') || lower.includes('protein') || lower.includes('macro') || lower.includes('diet') || lower.includes('calorie')) {
    return {
      reply: "Your current target is 2,200 kcal with 140g Protein, 240g Carbs, and 65g Fat. Aim to distribute protein evenly across 4 meals (35g per meal) to maintain a positive net nitrogen balance throughout your recovery phase.",
      actionableTip: "Consume 30-40g whey or casein post-workout within 60 minutes of session completion.",
      disclaimer: "All nutrition and macro values are estimates for general tracking purposes, not medical advice."
    };
  }

  if (lower.includes('water') || lower.includes('hydrate') || lower.includes('dehydrat')) {
    return {
      reply: "Optimal hydration is critical for muscle glycogen replenishment and cellular volume. Aim for 3.5L per day, adding 500ml per hour of high-intensity training.",
      actionableTip: "Include an electrolyte pinch of sodium and potassium during heavy squat or deadlift days.",
      disclaimer: "Hydration targets are general fitness estimates, not medical advice."
    };
  }

  if (lower.includes('recovery') || lower.includes('sleep') || lower.includes('cns') || lower.includes('fatigue')) {
    return {
      reply: "Your CNS Readiness score is 94% (Prime State). Autonomic balance indicates optimal HRV recovery. You can execute high-volume intensity sessions today without elevated risk of overreaching.",
      actionableTip: "Prioritize 8+ hours of nocturnal sleep and post-lift cold therapy.",
      disclaimer: "CNS & Biometric scores use sensor estimation algorithms and are not medical diagnoses."
    };
  }

  return {
    reply: `FitTrack AI Coach: Analyzing your query "${prompt}". Your performance metrics indicate solid consistency! Maintain disciplined macro distribution and execute planned mesocycle progressions for peak physiological output.`,
    actionableTip: "Log every set and meal in real time to maintain sub-1% telemetry variance.",
    disclaimer: "All fitness and nutritional outputs are estimates, not medical advice."
  };
};

// @route POST /api/ai/chat
router.post('/chat', protect, validate(aiChatSchema), async (req, res, next) => {
  try {
    const { message, context } = req.body;
    const aiResponse = generateAICoachResponse(message, context);
    
    res.json({
      sender: 'ai',
      timestamp: new Date().toISOString(),
      ...aiResponse
    });
  } catch (error) {
    next(error);
  }
});

// @route POST /api/ai/analyze-food
router.post('/analyze-food', protect, async (req, res, next) => {
  try {
    const { foodName, imageUrl } = req.body;
    
    // Simulated Computer Vision / AI Meal Analysis
    const recognizedFood = foodName || 'Grilled Salmon Bowl with Quinoa & Roasted Asparagus';
    const estimatedData = {
      foodName: recognizedFood,
      mealType: 'Lunch',
      calories: 580,
      proteinGrams: 46,
      carbsGrams: 42,
      fatGrams: 22,
      confidenceScore: 0.96,
      micronutrients: {
        omega3Grams: 2.4,
        fiberGrams: 6.5,
        sodiumMg: 420
      },
      analysisSummary: "High-protein lean meal detected. Excellent fatty acid profile and low glycemic carb sources ideal for post-workout anabolic recovery.",
      disclaimer: "All nutrition/health outputs are estimates generated by AI analysis, not medical advice."
    };

    res.json(estimatedData);
  } catch (error) {
    next(error);
  }
});

module.exports = router;
